#!/usr/bin/env python3
"""Generate a box-base pan flute .scad file from a JSON chord map."""

import json
import sys
import os

NOTE_BASES = {
    'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11
}

# Box-base dimensions (mm) — from profile.dxf / STL analysis
OUTER_X = 10.0          # outer width
OUTER_Y = 20.0          # outer depth (both tubes)
BORE_W = 7.0            # bore width  (X)
BORE_H = 7.75           # bore height (Y)
WALL = 1.5              # wall thickness (all sides + center wall)
BASE_RESONATING = 7.0   # resonating length inside box-base.stl
TUBE_SPACING = 10.0     # center-to-center X spacing (= outer width, flush)

# Bore Y positions relative to profile center (Y=0)
BORE_A_Y_START = -8.5   # bore A (Y-negative tube) Y-min
BORE_B_Y_START = 0.75   # bore B (Y-positive tube) Y-min

# Acoustic constants
SPEED_OF_SOUND = 343000.0   # mm/s at ~20 °C
END_CORR_FACTOR = 0.82      # empirical end-correction multiplier
D_H = 2 * BORE_W * BORE_H / (BORE_W + BORE_H)  # hydraulic diameter ≈ 7.356 mm

# Nameplate
BASE_Z_BOTTOM = -30.689     # bottom of box-base.stl (open/blowing end)
NAMEPLATE_DEPTH = 0.5       # impression depth (mm)
NAMEPLATE_SIZE = 6           # font size (mm)
NAMEPLATE_Z = BASE_Z_BOTTOM + 11  # just above the air escape holes

# Note labels on end caps
LABEL_DEPTH = 0.4           # impression depth (mm)
LABEL_SIZE = 3              # font size (mm)
TUBE_A_CAP_Y = -OUTER_Y / 4  # center of A half-profile (-5)
TUBE_B_CAP_Y = OUTER_Y / 4   # center of B half-profile (+5)


def parse_note(name):
    """Parse a note name like 'C#7' or 'Bb6' into its frequency (Hz)."""
    i = 0
    letter = name[i].upper()
    semitone = NOTE_BASES[letter]
    i += 1
    while i < len(name) and name[i] in ('#', 'b'):
        semitone += 1 if name[i] == '#' else -1
        i += 1
    octave = int(name[i:])
    midi = (octave + 1) * 12 + semitone
    return 440.0 * (2.0 ** ((midi - 69) / 12.0))


def extension_length(freq):
    """Extension above box-base needed to reach target resonating length."""
    target = SPEED_OF_SOUND / (4 * freq) - END_CORR_FACTOR * D_H
    return max(0.0, target - BASE_RESONATING)


def generate_scad(pairs, name="MARIO"):
    """Return a complete .scad file as a string."""
    L = []  # output lines
    w = L.append

    w("// Box-base pan flute — generated by generate_flute.py")
    w("// Do not edit by hand\n")

    n_cols = len(pairs)
    center_x = (n_cols - 1) * TUBE_SPACING / 2

    w("difference() {")
    w("  union() {")
    for i, (note_a, note_b) in enumerate(pairs):
        freq_a = parse_note(note_a)
        freq_b = parse_note(note_b)
        ext_a = extension_length(freq_a)
        ext_b = extension_length(freq_b)

        w(f"    // Column {i}: {note_a} ({freq_a:.1f} Hz) / {note_b} ({freq_b:.1f} Hz)")
        w(f"    // ext_a={ext_a:.2f}mm  ext_b={ext_b:.2f}mm")
        w(f"    translate([{i * TUBE_SPACING}, 0, 0]) {{")
        w(f'      import("box-base.stl", convexity=10);')

        # Tube A extension (Y-negative half)
        # ext_a = internal bore length; outer height = ext_a + WALL (cap)
        if ext_a > 0:
            w(f"      difference() {{")
            w(f"        // Tube A outer — {note_a}")
            w(f"        translate([{-OUTER_X/2}, {-OUTER_Y/2}, 0])")
            w(f"          cube([{OUTER_X}, {OUTER_Y/2}, {ext_a + WALL:.4f}]);")
            w(f"        translate([{-BORE_W/2}, {BORE_A_Y_START}, -0.01])")
            w(f"          cube([{BORE_W}, {BORE_H}, {ext_a + 0.01:.4f}]);")
            w(f"      }}")

        # Tube B extension (Y-positive half)
        if ext_b > 0:
            w(f"      difference() {{")
            w(f"        // Tube B outer — {note_b}")
            w(f"        translate([{-OUTER_X/2}, 0, 0])")
            w(f"          cube([{OUTER_X}, {OUTER_Y/2}, {ext_b + WALL:.4f}]);")
            w(f"        translate([{-BORE_W/2}, {BORE_B_Y_START}, -0.01])")
            w(f"          cube([{BORE_W}, {BORE_H}, {ext_b + 0.01:.4f}]);")
            w(f"      }}")

        w(f"    }}")
        w("")

    w("  }")
    w("")

    # Nameplate — impressed into front face (Y = -OUTER_Y/2)
    d = NAMEPLATE_DEPTH
    w(f"  // Nameplate: \"{name}\"")
    w(f"  translate([{center_x}, {-OUTER_Y/2 - 0.01}, {NAMEPLATE_Z}])")
    w(f"    rotate([-90, 0, 0])")
    w(f"      linear_extrude(height={d + 0.02})")
    w(f"        mirror([0, 1, 0])")
    w(f'          text("{name}", size={NAMEPLATE_SIZE}, font="Liberation Sans:style=Bold", halign="center", valign="center");')
    w("")

    # Note labels impressed into each tube's end cap (top surface, Z+)
    ld = LABEL_DEPTH
    for i, (note_a, note_b) in enumerate(pairs):
        freq_a = parse_note(note_a)
        freq_b = parse_note(note_b)
        ext_a = extension_length(freq_a)
        ext_b = extension_length(freq_b)
        cap_z_a = ext_a + WALL
        cap_z_b = ext_b + WALL

        w(f"  // Labels column {i}: {note_a} / {note_b}")
        w(f"  translate([{i * TUBE_SPACING}, {TUBE_A_CAP_Y}, {cap_z_a + 0.01}])")
        w(f"    mirror([0, 0, 1])")
        w(f"      linear_extrude(height={ld + 0.02})")
        w(f"        rotate([0, 0, 180])")
        w(f'          text("{note_a}", size={LABEL_SIZE}, font="Liberation Sans:style=Bold", halign="center", valign="center");')
        w(f"  translate([{i * TUBE_SPACING}, {TUBE_B_CAP_Y}, {cap_z_b + 0.01}])")
        w(f"    mirror([0, 0, 1])")
        w(f"      linear_extrude(height={ld + 0.02})")
        w(f"        rotate([0, 0, 180])")
        w(f'          text("{note_b}", size={LABEL_SIZE}, font="Liberation Sans:style=Bold", halign="center", valign="center");')
    w("")

    w("}")
    w("")
    return "\n".join(L)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <notes.json>", file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    name = sys.argv[2].upper() if len(sys.argv) > 2 else \
        os.path.splitext(os.path.basename(input_path))[0].upper()
    output_path = os.path.join(os.path.dirname(input_path) or '.', 'flute.scad')

    with open(input_path) as f:
        pairs = json.load(f)

    scad = generate_scad(pairs, name)
    with open(output_path, 'w') as f:
        f.write(scad)

    print(f"Wrote {output_path} — {len(pairs)} chord columns\n")
    for i, (note_a, note_b) in enumerate(pairs):
        freq_a, freq_b = parse_note(note_a), parse_note(note_b)
        ext_a, ext_b = extension_length(freq_a), extension_length(freq_b)
        print(f"  {i}: {note_a:>3s} {freq_a:7.1f}Hz ext={ext_a:6.2f}mm  |  "
              f"{note_b:>3s} {freq_b:7.1f}Hz ext={ext_b:6.2f}mm")


if __name__ == '__main__':
    main()
