#!/usr/bin/env python3
"""Convert a JSON file of note-name pairs into an OpenSCAD include file (notes.scad)."""

import json
import sys
import os

NOTE_BASES = {
    'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11
}

def parse_note(name):
    """Parse a note name like 'C#4' or 'Db3' into a MIDI number and frequency."""
    i = 0
    letter = name[i].upper()
    semitone = NOTE_BASES[letter]
    i += 1

    while i < len(name) and name[i] in ('#', 'b'):
        if name[i] == '#':
            semitone += 1
        else:
            semitone -= 1
        i += 1

    octave = int(name[i:])
    midi = (octave + 1) * 12 + semitone
    freq = 440.0 * (2.0 ** ((midi - 69) / 12.0))
    return midi, freq

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} notes.json", file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = os.path.join(os.path.dirname(input_path) or '.', 'notes.scad')

    with open(input_path) as f:
        pairs = json.load(f)

    lines = []
    lines.append("// Generated by generate_notes.py — do not edit by hand")
    lines.append("//")

    entries = []
    for pair in pairs:
        name_up, name_down = pair
        midi_up, freq_up = parse_note(name_up)
        midi_down, freq_down = parse_note(name_down)
        entries.append(f"  [{freq_up:.3f}, {freq_down:.3f}]")
        lines.append(f"// Column {len(entries)}: {name_up} ({freq_up:.2f} Hz) / {name_down} ({freq_down:.2f} Hz)")

    lines.append("")
    lines.append("note_pairs = [")
    lines.append(",\n".join(entries))
    lines.append("];")
    lines.append("")

    name_entries = []
    for pair in pairs:
        name_up, name_down = pair
        name_entries.append(f'  ["{name_up}", "{name_down}"]')
    lines.append("note_names = [")
    lines.append(",\n".join(name_entries))
    lines.append("];")
    lines.append("")

    with open(output_path, 'w') as f:
        f.write("\n".join(lines))

    print(f"Wrote {output_path} with {len(entries)} note pairs.")

if __name__ == '__main__':
    main()
